[build-system]
requires = ["setuptools>=61.0.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "Object Detection Model"
version = "1.0.1"
description = "UAFS AI Lab Capstone Project"
readme = "README.md"
authors = [{ name = "Marco Garcia", email = "mgarci14@uafs.edu" }]